# Generated by Django 4.2 on 2026-06-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('equipo_necesario', models.TextField(blank=True, null=True)),
                ('nivel_dificultad', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('url_video', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejercicio',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisito', models.TextField(blank=True, null=True)),
                ('valoracion_num', models.SmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Bloqueado', 'Bloqueado'), ('Alcanzado', 'Alcanzado')], max_length=12)),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logros',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_med', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_total', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_nivel', models.ForeignKey(db_column='id_nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nivel')),
            ],
            options={
                'db_table': 'rutina',
            },
        ),
        migrations.CreateModel(
            name='RutinaUsuario',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada'), ('Pausada', 'Pausada')], default='Activa', max_length=12)),
                ('adaptaciones_personalizadas', models.TextField(blank=True, null=True)),
                ('id_rutina', models.ForeignKey(db_column='id_rutina', on_delete=django.db.models.deletion.CASCADE, to='core.rutina')),
            ],
            options={
                'db_table': 'rutina_usuario',
            },
        ),
        migrations.CreateModel(
            name='TipoEjercicio',
            fields=[
                ('id_tipo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_ejercicio',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('Coach', 'Coach'), ('Usuario', 'Usuario')], max_length=20)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('objetivo', models.CharField(blank=True, max_length=100, null=True)),
                ('disciplina_preferida', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nivel_usuario', models.SmallIntegerField(blank=True, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('id_medida', models.ForeignKey(blank=True, db_column='id_medida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medida')),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.PROTECT, to='core.tipousuario')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='VideoEjercicio',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('ejercicio', models.ForeignKey(db_column='id_ejercicio', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.ejercicio')),
            ],
            options={
                'db_table': 'video_ejercicio',
            },
        ),
        migrations.CreateModel(
            name='ValoracionProfesional',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_valoracion', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_medida', models.ForeignKey(db_column='id_medida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medida')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'valoracion_profesional',
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('id_rutina_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rutinausuario')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('repeticiones_realizadas', models.SmallIntegerField(blank=True, null=True)),
                ('series_realizadas', models.SmallIntegerField(blank=True, null=True)),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_ejercicio', models.ForeignKey(db_column='id_ejercicio', on_delete=django.db.models.deletion.CASCADE, to='core.ejercicio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'seguimiento',
            },
        ),
        migrations.AddField(
            model_name='rutinausuario',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id_rutina_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('orden', models.SmallIntegerField(blank=True, null=True)),
                ('repeticiones', models.SmallIntegerField(blank=True, null=True)),
                ('series', models.SmallIntegerField(blank=True, null=True)),
                ('descanso', models.CharField(blank=True, max_length=20, null=True)),
                ('id_ejercicio', models.ForeignKey(db_column='id_ejercicio', on_delete=django.db.models.deletion.CASCADE, to='core.ejercicio')),
                ('id_rutina', models.ForeignKey(db_column='id_rutina', on_delete=django.db.models.deletion.CASCADE, to='core.rutina')),
            ],
            options={
                'db_table': 'rutina_ejercicio',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Leída', 'Leída'), ('No Leída', 'No Leída')], default='No Leída', max_length=10)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='EjercicioSesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False)),
                ('id_rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rutinaejercicio')),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionentrenamiento')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo_ejercicio',
            field=models.ForeignKey(db_column='tipo_ejercicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoejercicio'),
        ),
        migrations.CreateModel(
            name='RutinaUsuarioDia',
            fields=[
                ('id_rutina_usuario_dia', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('id_rutina_usuario', models.ForeignKey(db_column='id_rutina_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='core.rutinausuario')),
            ],
            options={
                'db_table': 'rutina_usuario_dia',
                'unique_together': {('id_rutina_usuario', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('fecha_obtenida', models.DateField(blank=True, null=True)),
                ('id_logro', models.ForeignKey(db_column='id_logro', on_delete=django.db.models.deletion.CASCADE, to='core.logro')),
            ],
            options={
                'db_table': 'usuario_logro',
                'unique_together': {('id_usuario', 'id_logro')},
            },
        ),
    ]
